### ISSUE TITLE
Missing `./template.json`

### ISSUE THREAD

**Issue by KellyKeKe** [Awenbocc/LLM-OOD#1]
Hello! I'm truly impressed by your work. However, when attempting to execute your code, I noticed the absence of the "./template.json" file, which I guess contains the prompts used for various datasets. Since the prompt plays a crucial role in the system's real-world performance, would it be possible for you to share this configuration as well? I'd greatly appreciate your assistance. Thank you!

**Comment by Awenbocc** [comment]
Hi, sorry for the late response!

We have released all codes, which help to reproduce results.

Thanks for your attention.

Best,
