### ISSUE TITLE
packages

### ISSUE THREAD

**Issue by mueller-mp** [Awenbocc/LLM-OOD#2]
Thanks for the code! Could you provide a list of packages with their versions that are required for reproducing your results? 
Alternatively, a .yml file would be great :)
Cheers, 
Max

**Comment by Awenbocc** [comment]
Hi, Max. Thanks for your attention and feedback. I have uploaded requirements.txt and dependencies.yml, which may solve your problem. 
Due to heavy ddls recently, sorry for the late response. 
Kelvin
