### ISSUE TITLE
Weights of the finetuned model

### ISSUE THREAD

**Issue by PrakharSaxena24** [Awenbocc/LLM-OOD#3]
thank you for the code. 
I am trying to run the code and it will be very helpful to have access to the finetuned model under fine_tuned_far_ood_run.sh and fine_tuned_near_ood_run.sh .
/home/bossjobai/LLM_Projects/weights/llama-7b

Thank you.

**Comment by Awenbocc** [comment]
Hi, thanks for your interest in this work. The llama-7b weights we used here (/home/bossjobai/LLM_Projects/weights/llama-7b) you can download from here: https://huggingface.co/huggyllama/llama-7b/tree/main.

**Comment by PrakharSaxena24** [comment]
Thanks!
